NSERT INTO CANDIDATE(CID, PARTY_NO, PARTY_NAME) VALUES('C1001','PA001','BJP');
INSERT INTO CANDIDATE(CID, PARTY_NO, PARTY_NAME)  VALUES('C1002','PA002','CONGRESS');
INSERT INTO CANDIDATE(CID, PARTY_NO, PARTY_NAME)  VALUES('C1003','PA003','CPI');
INSERT INTO CANDIDATE(CID, PARTY_NO, PARTY_NAME)  VALUES('C1004','PA004','AIADMK');
INSERT INTO CANDIDATE(CID, PARTY_NO, PARTY_NAME)  VALUES('C1005','PA005','AAP');
